export const START_SCREEN_STREAMING = "START_SCREEN_STREAMING"
export const STOP_SCREEN_STREAMING = "STOP_SCREEN_STREAMING"
export const MONITORS = "MONITORS"
export const KEY_EXECUTION = "KEY_EXECUTION"