export const START_WEBCAM = "START_WEBCAM"

export const START_DOWNLOAD = "START_DOWNLOAD"

export const WEBCAM_DEVICES = "WEBCAM_DEVICES"

export const STOP_WEBCAM = "STOP_WEBCAM"


export const START_RECORDING_WEBCAM = "START_RECORDING_WEBCAM"

export const STOP_RECORDING_WEBCAM = "STOP_RECORDING_WEBCAM"

export const SEND_WEBCAM_RECORDS = "SEND_WEBCAM_RECORDS"