package Information;

public enum Action {
    SYS_INFO, DISK, NET_INFO, R_A_DIR, R_FO_DIR, DOWNLOAD, COPY, DELETE, RUN, MOVE, UPLOAD, REQUEST_WEBCAM, START_WEBCAM,
    SHELL_COMMAND, KEYBOARD_COMMAND, BOX_MESSAGE, SCREEN_STREAM

}
