package Connections;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: packet.proto

public final class PacketOuterClass {
  private PacketOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PacketOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Packet)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 action = 1;</code>
     * @return The action.
     */
    int getAction();

    /**
     * <code>string value = 2;</code>
     * @return The value.
     */
    String getValue();
    /**
     * <code>string value = 2;</code>
     * @return The bytes for value.
     */
    com.google.protobuf.ByteString
        getValueBytes();

    /**
     * <code>repeated string first_values = 3;</code>
     * @return A list containing the firstValues.
     */
    java.util.List<String>
        getFirstValuesList();
    /**
     * <code>repeated string first_values = 3;</code>
     * @return The count of firstValues.
     */
    int getFirstValuesCount();
    /**
     * <code>repeated string first_values = 3;</code>
     * @param index The index of the element to return.
     * @return The firstValues at the given index.
     */
    String getFirstValues(int index);
    /**
     * <code>repeated string first_values = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the firstValues at the given index.
     */
    com.google.protobuf.ByteString
        getFirstValuesBytes(int index);

    /**
     * <code>repeated string second_values = 4;</code>
     * @return A list containing the secondValues.
     */
    java.util.List<String>
        getSecondValuesList();
    /**
     * <code>repeated string second_values = 4;</code>
     * @return The count of secondValues.
     */
    int getSecondValuesCount();
    /**
     * <code>repeated string second_values = 4;</code>
     * @param index The index of the element to return.
     * @return The secondValues at the given index.
     */
    String getSecondValues(int index);
    /**
     * <code>repeated string second_values = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the secondValues at the given index.
     */
    com.google.protobuf.ByteString
        getSecondValuesBytes(int index);
  }
  /**
   * Protobuf type {@code Packet}
   */
  public static final class Packet extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Packet)
      PacketOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Packet.newBuilder() to construct.
    private Packet(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Packet() {
      value_ = "";
      firstValues_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      secondValues_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new Packet();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PacketOuterClass.internal_static_Packet_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PacketOuterClass.internal_static_Packet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Packet.class, Builder.class);
    }

    public static final int ACTION_FIELD_NUMBER = 1;
    private int action_ = 0;
    /**
     * <code>int32 action = 1;</code>
     * @return The action.
     */
    @Override
    public int getAction() {
      return action_;
    }

    public static final int VALUE_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile Object value_ = "";
    /**
     * <code>string value = 2;</code>
     * @return The value.
     */
    @Override
    public String getValue() {
      Object ref = value_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        value_ = s;
        return s;
      }
    }
    /**
     * <code>string value = 2;</code>
     * @return The bytes for value.
     */
    @Override
    public com.google.protobuf.ByteString
        getValueBytes() {
      Object ref = value_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FIRST_VALUES_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private com.google.protobuf.LazyStringArrayList firstValues_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    /**
     * <code>repeated string first_values = 3;</code>
     * @return A list containing the firstValues.
     */
    public com.google.protobuf.ProtocolStringList
        getFirstValuesList() {
      return firstValues_;
    }
    /**
     * <code>repeated string first_values = 3;</code>
     * @return The count of firstValues.
     */
    public int getFirstValuesCount() {
      return firstValues_.size();
    }
    /**
     * <code>repeated string first_values = 3;</code>
     * @param index The index of the element to return.
     * @return The firstValues at the given index.
     */
    public String getFirstValues(int index) {
      return firstValues_.get(index);
    }
    /**
     * <code>repeated string first_values = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the firstValues at the given index.
     */
    public com.google.protobuf.ByteString
        getFirstValuesBytes(int index) {
      return firstValues_.getByteString(index);
    }

    public static final int SECOND_VALUES_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private com.google.protobuf.LazyStringArrayList secondValues_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    /**
     * <code>repeated string second_values = 4;</code>
     * @return A list containing the secondValues.
     */
    public com.google.protobuf.ProtocolStringList
        getSecondValuesList() {
      return secondValues_;
    }
    /**
     * <code>repeated string second_values = 4;</code>
     * @return The count of secondValues.
     */
    public int getSecondValuesCount() {
      return secondValues_.size();
    }
    /**
     * <code>repeated string second_values = 4;</code>
     * @param index The index of the element to return.
     * @return The secondValues at the given index.
     */
    public String getSecondValues(int index) {
      return secondValues_.get(index);
    }
    /**
     * <code>repeated string second_values = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the secondValues at the given index.
     */
    public com.google.protobuf.ByteString
        getSecondValuesBytes(int index) {
      return secondValues_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (action_ != 0) {
        output.writeInt32(1, action_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(value_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, value_);
      }
      for (int i = 0; i < firstValues_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, firstValues_.getRaw(i));
      }
      for (int i = 0; i < secondValues_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, secondValues_.getRaw(i));
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (action_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, action_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(value_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, value_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < firstValues_.size(); i++) {
          dataSize += computeStringSizeNoTag(firstValues_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getFirstValuesList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < secondValues_.size(); i++) {
          dataSize += computeStringSizeNoTag(secondValues_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getSecondValuesList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Packet)) {
        return super.equals(obj);
      }
      Packet other = (Packet) obj;

      if (getAction()
          != other.getAction()) return false;
      if (!getValue()
          .equals(other.getValue())) return false;
      if (!getFirstValuesList()
          .equals(other.getFirstValuesList())) return false;
      if (!getSecondValuesList()
          .equals(other.getSecondValuesList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ACTION_FIELD_NUMBER;
      hash = (53 * hash) + getAction();
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getValue().hashCode();
      if (getFirstValuesCount() > 0) {
        hash = (37 * hash) + FIRST_VALUES_FIELD_NUMBER;
        hash = (53 * hash) + getFirstValuesList().hashCode();
      }
      if (getSecondValuesCount() > 0) {
        hash = (37 * hash) + SECOND_VALUES_FIELD_NUMBER;
        hash = (53 * hash) + getSecondValuesList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Packet parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Packet parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Packet parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Packet parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Packet parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Packet parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Packet parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Packet parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Packet parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static Packet parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Packet parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Packet parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Packet prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Packet}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Packet)
        PacketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PacketOuterClass.internal_static_Packet_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PacketOuterClass.internal_static_Packet_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Packet.class, Builder.class);
      }

      // Construct using PacketOuterClass.Packet.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        action_ = 0;
        value_ = "";
        firstValues_ =
            com.google.protobuf.LazyStringArrayList.emptyList();
        secondValues_ =
            com.google.protobuf.LazyStringArrayList.emptyList();
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return PacketOuterClass.internal_static_Packet_descriptor;
      }

      @Override
      public Packet getDefaultInstanceForType() {
        return Packet.getDefaultInstance();
      }

      @Override
      public Packet build() {
        Packet result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Packet buildPartial() {
        Packet result = new Packet(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(Packet result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.action_ = action_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.value_ = value_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          firstValues_.makeImmutable();
          result.firstValues_ = firstValues_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          secondValues_.makeImmutable();
          result.secondValues_ = secondValues_;
        }
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Packet) {
          return mergeFrom((Packet)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Packet other) {
        if (other == Packet.getDefaultInstance()) return this;
        if (other.getAction() != 0) {
          setAction(other.getAction());
        }
        if (!other.getValue().isEmpty()) {
          value_ = other.value_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.firstValues_.isEmpty()) {
          if (firstValues_.isEmpty()) {
            firstValues_ = other.firstValues_;
            bitField0_ |= 0x00000004;
          } else {
            ensureFirstValuesIsMutable();
            firstValues_.addAll(other.firstValues_);
          }
          onChanged();
        }
        if (!other.secondValues_.isEmpty()) {
          if (secondValues_.isEmpty()) {
            secondValues_ = other.secondValues_;
            bitField0_ |= 0x00000008;
          } else {
            ensureSecondValuesIsMutable();
            secondValues_.addAll(other.secondValues_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                action_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                value_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                String s = input.readStringRequireUtf8();
                ensureFirstValuesIsMutable();
                firstValues_.add(s);
                break;
              } // case 26
              case 34: {
                String s = input.readStringRequireUtf8();
                ensureSecondValuesIsMutable();
                secondValues_.add(s);
                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int action_ ;
      /**
       * <code>int32 action = 1;</code>
       * @return The action.
       */
      @Override
      public int getAction() {
        return action_;
      }
      /**
       * <code>int32 action = 1;</code>
       * @param value The action to set.
       * @return This builder for chaining.
       */
      public Builder setAction(int value) {

        action_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 action = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearAction() {
        bitField0_ = (bitField0_ & ~0x00000001);
        action_ = 0;
        onChanged();
        return this;
      }

      private Object value_ = "";
      /**
       * <code>string value = 2;</code>
       * @return The value.
       */
      public String getValue() {
        Object ref = value_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          value_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string value = 2;</code>
       * @return The bytes for value.
       */
      public com.google.protobuf.ByteString
          getValueBytes() {
        Object ref = value_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string value = 2;</code>
       * @param value The value to set.
       * @return This builder for chaining.
       */
      public Builder setValue(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        value_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string value = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearValue() {
        value_ = getDefaultInstance().getValue();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string value = 2;</code>
       * @param value The bytes for value to set.
       * @return This builder for chaining.
       */
      public Builder setValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        value_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringArrayList firstValues_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      private void ensureFirstValuesIsMutable() {
        if (!firstValues_.isModifiable()) {
          firstValues_ = new com.google.protobuf.LazyStringArrayList(firstValues_);
        }
        bitField0_ |= 0x00000004;
      }
      /**
       * <code>repeated string first_values = 3;</code>
       * @return A list containing the firstValues.
       */
      public com.google.protobuf.ProtocolStringList
          getFirstValuesList() {
        firstValues_.makeImmutable();
        return firstValues_;
      }
      /**
       * <code>repeated string first_values = 3;</code>
       * @return The count of firstValues.
       */
      public int getFirstValuesCount() {
        return firstValues_.size();
      }
      /**
       * <code>repeated string first_values = 3;</code>
       * @param index The index of the element to return.
       * @return The firstValues at the given index.
       */
      public String getFirstValues(int index) {
        return firstValues_.get(index);
      }
      /**
       * <code>repeated string first_values = 3;</code>
       * @param index The index of the value to return.
       * @return The bytes of the firstValues at the given index.
       */
      public com.google.protobuf.ByteString
          getFirstValuesBytes(int index) {
        return firstValues_.getByteString(index);
      }
      /**
       * <code>repeated string first_values = 3;</code>
       * @param index The index to set the value at.
       * @param value The firstValues to set.
       * @return This builder for chaining.
       */
      public Builder setFirstValues(
          int index, String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureFirstValuesIsMutable();
        firstValues_.set(index, value);
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string first_values = 3;</code>
       * @param value The firstValues to add.
       * @return This builder for chaining.
       */
      public Builder addFirstValues(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureFirstValuesIsMutable();
        firstValues_.add(value);
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string first_values = 3;</code>
       * @param values The firstValues to add.
       * @return This builder for chaining.
       */
      public Builder addAllFirstValues(
          Iterable<String> values) {
        ensureFirstValuesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, firstValues_);
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string first_values = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearFirstValues() {
        firstValues_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string first_values = 3;</code>
       * @param value The bytes of the firstValues to add.
       * @return This builder for chaining.
       */
      public Builder addFirstValuesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        ensureFirstValuesIsMutable();
        firstValues_.add(value);
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringArrayList secondValues_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      private void ensureSecondValuesIsMutable() {
        if (!secondValues_.isModifiable()) {
          secondValues_ = new com.google.protobuf.LazyStringArrayList(secondValues_);
        }
        bitField0_ |= 0x00000008;
      }
      /**
       * <code>repeated string second_values = 4;</code>
       * @return A list containing the secondValues.
       */
      public com.google.protobuf.ProtocolStringList
          getSecondValuesList() {
        secondValues_.makeImmutable();
        return secondValues_;
      }
      /**
       * <code>repeated string second_values = 4;</code>
       * @return The count of secondValues.
       */
      public int getSecondValuesCount() {
        return secondValues_.size();
      }
      /**
       * <code>repeated string second_values = 4;</code>
       * @param index The index of the element to return.
       * @return The secondValues at the given index.
       */
      public String getSecondValues(int index) {
        return secondValues_.get(index);
      }
      /**
       * <code>repeated string second_values = 4;</code>
       * @param index The index of the value to return.
       * @return The bytes of the secondValues at the given index.
       */
      public com.google.protobuf.ByteString
          getSecondValuesBytes(int index) {
        return secondValues_.getByteString(index);
      }
      /**
       * <code>repeated string second_values = 4;</code>
       * @param index The index to set the value at.
       * @param value The secondValues to set.
       * @return This builder for chaining.
       */
      public Builder setSecondValues(
          int index, String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureSecondValuesIsMutable();
        secondValues_.set(index, value);
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string second_values = 4;</code>
       * @param value The secondValues to add.
       * @return This builder for chaining.
       */
      public Builder addSecondValues(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureSecondValuesIsMutable();
        secondValues_.add(value);
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string second_values = 4;</code>
       * @param values The secondValues to add.
       * @return This builder for chaining.
       */
      public Builder addAllSecondValues(
          Iterable<String> values) {
        ensureSecondValuesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, secondValues_);
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string second_values = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearSecondValues() {
        secondValues_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string second_values = 4;</code>
       * @param value The bytes of the secondValues to add.
       * @return This builder for chaining.
       */
      public Builder addSecondValuesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        ensureSecondValuesIsMutable();
        secondValues_.add(value);
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Packet)
    }

    // @@protoc_insertion_point(class_scope:Packet)
    private static final Packet DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Packet();
    }

    public static Packet getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Packet>
        PARSER = new com.google.protobuf.AbstractParser<Packet>() {
      @Override
      public Packet parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Packet> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Packet> getParserForType() {
      return PARSER;
    }

    @Override
    public Packet getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Packet_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Packet_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\014packet.proto\"T\n\006Packet\022\016\n\006action\030\001 \001(\005" +
      "\022\r\n\005value\030\002 \001(\t\022\024\n\014first_values\030\003 \003(\t\022\025\n" +
      "\rsecond_values\030\004 \003(\tb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Packet_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Packet_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Packet_descriptor,
        new String[] { "Action", "Value", "FirstValues", "SecondValues", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
